### ISSUE TITLE
图片预览

### ISSUE THREAD

**Issue by WwWxQxQ** [cyanzhong/Image-Uploader#2]
> Desc

当图片的路径是Gitee的时候，由于Gitee图床默认大于`1MB`的图片都需要登陆查看，所以很多情况下都会变成这样 （不是Github图片挂了，是这图片本来就是挂了的hhh）

<img width="114" alt="截屏2022-04-09 下午1 29 13" src="https://user-images.githubusercontent.com/68727310/162557885-51960292-c3c2-4105-aa47-d03ecffc79a0.png">

由于我是直接从typora里cv过来的，typora里没问题，感觉是不是需要在请求的时候带一点认证信息

**Comment by cyanzhong** [comment]
感谢反馈，不过我准备什么也不做。我在微博上被私信说 Gitee 在打击外链图片，所以我做什么意义都不大。

<img src="https://user-images.githubusercontent.com/6745066/162604559-f301753e-4cbc-4336-9044-ce5fb9ea63cc.PNG" width="360px" >

**Comment by WwWxQxQ** [comment]
那完全可以理解了，看来还是找一个纯粹的图床服务比较稳妥，感谢钟大回复 😆
