### ISSUE TITLE
能否支持backblaze

### ISSUE THREAD

**Issue by kkfive** [cyanzhong/Image-Uploader#3]
地址：https://www.backblaze.com/b2/sign-up.html

**Comment by Moraxyc** [comment]
附议，自定义里提供的借口不足以使用b2的api

**Comment by cyanzhong** [comment]
不是不行，只是我最近没有空闲来做这个支持，很抱歉。

这里有个文档：https://github.com/cyanzhong/Image-Uploader/blob/main/DOCS_CN.md 如果你们知道怎么做的话，欢迎开个 PR。

**Comment by cyanzhong** [comment]
已支持。

**Comment by kkfive** [comment]
> 已支持。

感谢
