### ISSUE TITLE
Cloudflare推出了R2存储桶，希望支持

### ISSUE THREAD

**Issue by Moraxyc** [cyanzhong/Image-Uploader#5]
如题
感觉通过worker调用方法比较简单，等会儿研究下。希望官方支持。

[Cloudflare R2文档](https://developers.cloudflare.com/r2/)

**Comment by cyanzhong** [comment]
我无法测试，点击购买之后不会完成。

<img width="510" alt="image" src="https://user-images.githubusercontent.com/6745066/168229333-b2314a36-61fa-4570-b1dd-15762b86cb53.png">

**Comment by cyanzhong** [comment]
我只能说 Beta 阶段问题实在是太多了。一开始购买无法完成，现在我是上传文件不会显示。而且我也没找到把存储桶设置为 public 的方法。

**Comment by cyanzhong** [comment]
我准备至少等到完全能通过 Cloudflare 的 portal 操作所有事情才做这件事。

**Comment by Moraxyc** [comment]
OK
